os: linux
dist: focal
language: cpp

install:
 - sudo apt-get update
 - sudo apt-get install --yes libgtest-dev
 
 - sudo apt-get install clang-format
 - sudo apt-get install clang-tidy
 - sudo apt-get install valgrind
 - sudo apt-get install cppcheck

 - sudo pip install scan-build
 - sudo pip install cpplint
 - sudo pip install gcovr

env:
 - BUILD=Debug
 - BUILD=Release

script:
 - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD
 - make -C build
 - cd build && ctest --output-on-failure

jobs:
 include:
  - stage: TestCoverage
    script:
     - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=1
     - make -C build all test
     - curl -Os https://uploader.codecov.io/latest/linux/codecov
     - chmod +x codecov
     - ./codecov -f <(gcovr -e '.*/tests/.*' -x)
  - stage: Sanitaize
    script:
     - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DWITH_SANITIZERS=1
     - make -C build
     - cd build && make coverage
  - stage: Valgrind
    script:
     - cmake -B build -DCMAKE_BUILD_TYPE=Debug -WITH_VALGRIND=1
     - make -C build
     - cd build/lib/users/tests/ && valgrind --leak-check=yes ./runUnitTests_valgrind
